/* ============================================================
   ADD STUDENT (New Admission + Existing)
   ============================================================ */
function renderAddStudent(params={}) {
  // BUG-P05 FIX: type:'edit' was never handled — renderAddStudent rendered a blank new-admission
  // form instead. Redirect to the correct edit modal immediately.
  // Pop the nav stack entry pushNav just added so the Back button still works after closing.
  if (params.type === 'edit' && params.id) {
    if (Array.isArray(navStack) && navStack.length) navStack.pop();
    showEditStudentModal(params.id);
    return;
  }
  const isExisting = params.type === 'existing';
  setContent(`
    <div class="page-head">
      <div class="page-title">${isExisting ? 'Onboard Existing Student' : 'New Admission'}</div>
      <div class="page-sub">${isExisting ? 'Import a student with historical fee records.' : 'Enroll a new student into the system.'}</div>
    </div>
    <div class="card">
      <div class="card-hdr"><span class="card-title">Student Details</span></div>
      <div class="card-body">
        <div id="addStudentAlert"></div>
        <!-- COLONEL'S CHANGE #2: Removed DOB, Date of Admission, PEN, Address, Previous School, Fee Waiver. CHG-006: Fee S.No also removed. -->
        <div class="form-section-title">Personal Information</div>
        <div class="form-row">
          <div class="form-group"><label class="form-label">Full Name *</label><input class="form-control" id="fs_name" placeholder="Student's full name"></div>
          <div class="form-group">
            <label class="form-label">Gender *</label>
            <select class="form-control" id="fs_gender" onchange="syncBlockFromGender('fs_gender','fs_block')">
              <option value="">Select gender</option>
              <option>Male</option><option>Female</option><option>Other</option>
            </select>
          </div>
        </div>

        <div class="form-section-title">Block Assignment</div>
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">Block *</label>
            <select class="form-control" id="fs_block">
              <option value="">Select block</option>
              ${getBlocks().map(b=>'<option>'+b+'</option>').join('')}
            </select>
            <div style="font-size:11px;color:var(--muted);margin-top:4px">
              Auto-assigned from gender (Male → Boys Block, Female → Girls Block). Select <strong>Other</strong> to assign manually.
            </div>
          </div>
        </div>

        <div class="form-section-title">Academic Details</div>
        <div class="form-row-3">
          <div class="form-group">
            <label class="form-label">Class *</label>
            <select class="form-control" id="fs_class" onchange="(function(){const el=document.getElementById('fs_monthlyFee');if(el){el.value=_FEE_SCHEDULE[this.value]||''}; _fsCurYearRebuildGrid();}).call(this)">
              <option value="">Select class</option>
              ${getClassList().map(c=>'<option>'+c+'</option>').join('')}<!-- BUG-H02 FIX: dynamic class list -->
            </select>
          </div>
          <div class="form-group">
            <label class="form-label">Section *</label>
            <!-- BUG-N09 FIX: Dynamically populated from getSections() instead of hardcoded A/B/C.
                 Colonel's school continues to see A, B, C via the _DEFAULT_SECTIONS fallback. -->
            <select class="form-control" id="fs_section">
              <option value="">Select section</option>
              ${getSections().map(s=>'<option>'+s+'</option>').join('')}
            </select>
          </div>
          <!-- [CHG-020] Roll Number field removed universally -->
        </div>
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">Admission Number
              <span style="font-size:10px;color:var(--success);font-weight:400;text-transform:none;margin-left:6px">✦ Auto-generated (ADM-YYYY-NNN)</span>
            </label>
            <input class="form-control" id="fs_admNo" placeholder="Generating…" readonly
              style="background:rgba(82,200,122,0.07);border-color:rgba(82,200,122,0.30);color:var(--silver-lt);cursor:not-allowed"
              title="Admission Number is auto-generated by the system per CHG-014">
          </div>
          <!-- CHG-006: Fee S.No field removed platform-wide -->
        </div>
        <!-- CHG-014: Date of Admission — required field -->
        <div class="form-row">
          <div class="form-group">
            <label class="form-label">Date of Admission *
              <span style="font-size:10px;color:var(--muted);font-weight:400;text-transform:none;margin-left:6px">Used for "New Admissions This Month" stat and audit trail</span>
            </label>
            <input type="date" class="form-control" id="fs_admissionDate" value="${(()=>{const _d=nowIST();return `${_d.getFullYear()}-${String(_d.getMonth()+1).padStart(2,'0')}-${String(_d.getDate()).padStart(2,'0')}`;})() /* BUG-TS-001 FIX */}">
          </div>
        </div>

        <div class="form-section-title">Parent / Guardian</div>
        <div class="form-row">
          <div class="form-group"><label class="form-label">Parent / Guardian Name *</label><input class="form-control" id="fs_parent" placeholder="Full name"></div>
          <div class="form-group"><label class="form-label">Contact Number *</label><input class="form-control" id="fs_contact" type="tel" inputmode="numeric" maxlength="10" placeholder="10-digit mobile number" oninput="this.value=this.value.replace(/[^0-9]/g,'').slice(0,10)"></div>
        </div>

        ${isExisting ? `
        <div class="form-section-title">History Fee Information</div>
        <!-- BUG-M07 FIX: Monthly fee is auto-calculated from _FEE_SCHEDULE based on class.
             The free-text monthlyFee input was removed — it bypassed the Phase 3 fee lock.
             Only the opening outstanding balance (historical dues carried forward) is editable. -->
        <div class="form-row">
          <div class="form-group">
            <label class="form-label" style="display:flex;align-items:center;gap:8px">
              Fee Option (₹)  <!-- [CHG-015] Monthly Fee → Fee Option -->
              <span style="font-size:10px;font-weight:400;color:var(--warn);background:rgba(212,150,42,0.12);padding:2px 8px;border-radius:4px">🔒 Auto from class</span>
            </label>
            <input type="number" class="form-control" id="fs_monthlyFee" readonly
              style="background:var(--depth);color:var(--gold-lt);font-weight:700;cursor:not-allowed;border-color:rgba(212,150,42,0.3)"
              placeholder="Select class above">
            <div style="font-size:11px;color:var(--muted);margin-top:4px">Determined by class fee schedule — cannot be overridden.</div>
          </div>
          <div class="form-group" style="grid-column:1/-1">
            <label class="form-label">Opening Outstanding Balance
              <span style="font-size:10px;font-weight:400;color:var(--muted);margin-left:6px">Historical dues from previous class — carried forward into this system (multiple years supported)</span>
            </label>

            <!-- MULTI-YEAR DUES CONTAINER -->
            <div id="fs_prevDuesContainer" style="display:flex;flex-direction:column;gap:14px;margin-bottom:12px"></div>

            <!-- Add another year button -->
            <button type="button" onclick="_fsAddDuesRow()" style="
              background:rgba(74,158,202,0.10);border:1px dashed rgba(74,158,202,0.45);
              color:var(--info);border-radius:8px;padding:8px 18px;font-size:13px;
              font-weight:600;cursor:pointer;width:100%;transition:all 0.15s">
              ＋ Add Previous Year Dues Entry
            </button>

            <!-- Grand total across all years -->
            <div id="fs_prevDuesGrandTotalWrap" style="display:none;margin-top:10px;
              padding:10px 16px;border-radius:8px;background:rgba(201,168,76,0.08);
              border:1px solid rgba(201,168,76,0.25);display:flex;align-items:center;gap:12px">
              <span style="font-size:12px;color:var(--muted)">Total Opening Outstanding (all years):</span>
              <span id="fs_prevDuesGrandTotal" style="font-size:18px;font-weight:700;color:var(--gold-lt)">₹0</span>
            </div>

            <!-- Hidden field: JSON array of all dues rows — read by saveStudent() -->
            <input type="hidden" id="fs_prevDuesJson" value="[]">

            <!-- Legacy hidden fields kept for backward-compat read in saveStudent() — populated from first row -->
            <input type="hidden" id="fs_outstandingMonthsJson" value="[]">
            <input type="hidden" id="fs_outstandingYearValue" value="">
            <!-- Dummy elements so old _fsOutstandingRecalc references don't throw -->
            <input type="hidden" id="fs_outstanding" value="">
            <input type="hidden" id="fs_outstandingMonthCount" value="">
          </div>

          <!-- ── CURRENT YEAR DUES SECTION ── -->
          <div class="form-group" style="grid-column:1/-1;margin-top:18px;
               padding:16px 18px;border-radius:12px;
               background:rgba(74,158,202,0.06);
               border:1px solid rgba(74,158,202,0.22)">
            <label class="form-label" style="color:var(--info);margin-bottom:4px">
              Current Year Dues
              <span style="font-size:10px;font-weight:400;color:var(--muted);margin-left:6px">
                Months unpaid so far this academic year (${_getCurrentAcademicYearStr()})
              </span>
            </label>
            <div style="font-size:11px;color:var(--muted);margin-bottom:12px">
              All elapsed months are shown <span style="color:var(--danger);font-weight:600">RED = unpaid (due)</span>. Click a month to mark it <span style="color:var(--success);font-weight:600">GREEN = paid</span>. Only red (unpaid) months are stored as dues.
            </div>

            <!-- Month pill grid — populated by JS after class is chosen -->
            <div id="fs_curYearMonthWrap">
              <div id="fs_curYearMonthGrid" style="display:grid;grid-template-columns:repeat(6,1fr);gap:6px"></div>
            </div>

            <!-- Computed total -->
            <div id="fs_curYearAmountWrap" style="margin-top:10px;display:flex;align-items:center;gap:10px;flex-wrap:wrap">
              <label style="font-size:12px;color:var(--muted);white-space:nowrap">Total Due:</label>
              <input type="number" class="form-control" id="fs_curYearBalance" readonly
                style="max-width:160px;background:var(--depth);color:#7ac0e0;font-weight:700;
                       cursor:not-allowed;border-color:rgba(74,158,202,0.35)"
                placeholder="₹ 0">
              <span id="fs_curYearMonthCount" style="font-size:11px;color:var(--muted)"></span>
            </div>
            <div style="font-size:11px;color:var(--muted);margin-top:4px">
              <span id="fs_curYearRateLabel"></span>
            </div>

            <!-- Hidden fields -->
            <input type="hidden" id="fs_curYearMonthsJson" value="[]">
          </div>
        </div>
        ` : ''}

        <div style="margin-top:24px; display:flex; gap:12px">
          <button class="btn btn-primary" id="saveStudentBtn" onclick="saveStudent(${isExisting})">
            ${iconPlus} ${isExisting?'Import Student':'Save Student'}
          </button>
          <button class="btn btn-ghost" onclick="goBack()">Cancel</button>
        </div>
      </div>
    </div>
  `);
  // ADM-FIX: For NEW admission → generate the next sequential ADM number using
  // the year from the admissionDate field (so ADM-2024-NNN vs ADM-2025-NNN is correct).
  // Re-generates whenever staff changes the admissionDate.
  // For EXISTING student → no auto-generate; number assigned only at save time using
  // the student's actual due/admission year.
  if (!isExisting) {
    function _refreshAdmNo() {
      const dateEl = document.getElementById('fs_admissionDate');
      const yr = dateEl && dateEl.value
        ? String(new Date(dateEl.value).getFullYear())
        : String(nowIST().getFullYear());
      generateNextAdmNoForYear(yr).then(admNo => {
        const el = document.getElementById('fs_admNo');
        if (el) el.value = admNo;
      });
    }
    _refreshAdmNo();
    // Re-check whenever staff picks a different admission date
    const dateInput = document.getElementById('fs_admissionDate');
    if (dateInput) dateInput.addEventListener('change', _refreshAdmNo);
  } else {
    const el = document.getElementById('fs_admNo');
    if (el) {
      el.placeholder = 'Assigned on save using student\'s admission year';
      el.value = '';
    }
  }

  // MULTI-YEAR: For existing student, auto-add the first dues row
  if (isExisting) {
    _fsAddDuesRow();
  }
}

// ── MULTI-YEAR DUES SYSTEM ───────────────────────────────────────────────────
// Allows adding multiple previous-year dues rows (one per academic year).
// Each row has: Previous Class select + Academic Year select + Month grid + Amount.
// saveStudent() reads fs_prevDuesJson (array of all rows).

let _fsDuesRowCount = 0; // auto-increment row IDs

function _fsGetYearOptions() {
  const now = nowIST(); /* ITEM 01 FIX: IST, not device timezone */
  const curStart = _getAcademicYear().yearStart;   // L3: one definition of the June boundary
  let opts = '<option value="">— select year —</option>';
  // JSS-REF-VELTRIX-2026-005 ITEM 7: opening dues are only ever carried forward for the last TWO
  // academic years, so offer exactly those. ROLLING, not hardcoded — curStart is derived from
  // today's IST date above, so the window shifts automatically each academic year with no code
  // change (in 2026-27 this yields 2025-26 + 2024-25; in 2027-28 it yields 2026-27 + 2025-26).
  const _PREV_YEARS_OFFERED = 2;
  for (let i = 1; i <= _PREV_YEARS_OFFERED; i++) {
    const s = curStart - i;
    opts += `<option value="${s}-${s+1}">${s}–${s+1}</option>`;
  }
  return opts;
}

function _fsAddDuesRow() {
  const container = document.getElementById('fs_prevDuesContainer');
  if (!container) return;

  const rowId = ++_fsDuesRowCount;
  const clsOptions = '<option value="">— select class —</option>' +
    getClassList().map(c => `<option>${c}</option>`).join('');

  const rowEl = document.createElement('div');
  rowEl.id = `fs_duesRow_${rowId}`;
  rowEl.style.cssText = 'background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.10);border-radius:10px;padding:14px 16px;position:relative';
  rowEl.innerHTML = `
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:10px">
      <span style="font-size:12px;font-weight:700;color:var(--muted);text-transform:uppercase;letter-spacing:0.5px">
        Previous Year Dues Entry #${rowId}
      </span>
      <button type="button" onclick="_fsRemoveDuesRow(${rowId})"
        style="background:rgba(224,82,82,0.12);border:1px solid rgba(224,82,82,0.35);
               color:var(--danger);border-radius:6px;padding:3px 10px;font-size:11px;
               cursor:pointer;font-weight:600">✕ Remove</button>
    </div>
    <!-- Row 1: Class + Year -->
    <div style="display:flex;align-items:center;gap:14px;margin-bottom:10px;flex-wrap:wrap">
      <div style="display:flex;align-items:center;gap:8px">
        <label style="font-size:12px;color:var(--muted);white-space:nowrap">Previous Class:</label>
        <select class="form-control" id="fs_drCls_${rowId}" style="max-width:170px"
          onchange="_fsDuesRowRecalc(${rowId})">
          ${clsOptions}
        </select>
      </div>
      <div style="display:flex;align-items:center;gap:8px">
        <label style="font-size:12px;color:var(--muted);white-space:nowrap">Academic Year:</label>
        <select class="form-control" id="fs_drYear_${rowId}" style="max-width:170px"
          onchange="_fsDuesRowYearChange(${rowId})">
          ${_fsGetYearOptions()}
        </select>
      </div>
    </div>
    <!-- Month grid (revealed after year chosen) -->
    <div id="fs_drMonthWrap_${rowId}" style="display:none;margin-bottom:10px">
      <div style="font-size:11px;color:var(--success);margin-bottom:8px;font-weight:600">
        ✅ Click months that are PAID (green = paid · red = due)
      </div>
      <div id="fs_drMonthGrid_${rowId}" style="display:grid;grid-template-columns:repeat(6,1fr);gap:6px"></div>
    </div>
    <!-- Amount row -->
    <div id="fs_drAmtWrap_${rowId}" style="display:none;margin-top:8px;display:flex;align-items:center;gap:10px;flex-wrap:wrap">
      <label style="font-size:12px;color:var(--muted);white-space:nowrap">Total Outstanding:</label>
      <input type="number" id="fs_drAmt_${rowId}" readonly
        style="max-width:160px;background:var(--depth);color:var(--gold-lt);font-weight:700;
               cursor:not-allowed;border:1px solid rgba(201,168,76,0.35);border-radius:8px;
               padding:8px 12px;font-size:14px" placeholder="₹ 0">
      <span id="fs_drCount_${rowId}" style="font-size:11px;color:var(--muted)"></span>
    </div>
    <div id="fs_drRateLabel_${rowId}" style="font-size:11px;color:var(--muted);margin-top:4px"></div>
  `;
  container.appendChild(rowEl);
  _fsUpdateGrandTotal();
}

function _fsRemoveDuesRow(rowId) {
  const el = document.getElementById(`fs_duesRow_${rowId}`);
  if (el) el.remove();
  _fsUpdateGrandTotal();
  _fsSerializeDues();
}

function _fsDuesRowYearChange(rowId) {
  const yearSel  = document.getElementById(`fs_drYear_${rowId}`);
  const monthWrap= document.getElementById(`fs_drMonthWrap_${rowId}`);
  const amtWrap  = document.getElementById(`fs_drAmtWrap_${rowId}`);
  const grid     = document.getElementById(`fs_drMonthGrid_${rowId}`);
  if (!yearSel || !grid) return;

  const year = yearSel.value;
  if (!year) {
    if (monthWrap) monthWrap.style.display = 'none';
    if (amtWrap)  amtWrap.style.display   = 'none';
    return;
  }

  const MONTHS = ['June','July','August','September','October','November','December',
                  'January','February','March','April','May'];
  grid.innerHTML = MONTHS.map(m => `
    <button type="button"
      data-month="${m}" data-paid="0"
      onclick="_fsDuesRowToggleMonth(this, ${rowId})"
      style="padding:7px 4px;border-radius:8px;border:1px solid rgba(224,82,82,0.55);
             background:rgba(224,82,82,0.15);color:var(--danger);font-size:12px;
             font-weight:600;cursor:pointer;transition:all 0.15s;text-align:center;"
      title="${m} — unpaid">
      ${m.slice(0,3)}
    </button>`).join('');

  if (monthWrap) monthWrap.style.display = '';
  if (amtWrap)  amtWrap.style.display   = 'flex';
  _fsDuesRowRecalc(rowId);
}

function _fsDuesRowToggleMonth(btn, rowId) {
  const isPaid = btn.dataset.paid === '1';
  if (isPaid) {
    btn.dataset.paid     = '0';
    btn.style.background  = 'rgba(224,82,82,0.15)';
    btn.style.borderColor = 'rgba(224,82,82,0.55)';
    btn.style.color       = 'var(--danger)';
    btn.style.cursor      = 'pointer';
    btn.style.opacity     = '1';
    btn.innerHTML = btn.dataset.month.slice(0,3);
    btn.title = btn.dataset.month + ' — unpaid';
  } else {
    btn.dataset.paid     = '1';
    btn.style.background  = 'rgba(82,200,122,0.18)';
    btn.style.borderColor = 'rgba(82,200,122,0.55)';
    btn.style.color       = 'var(--success)';
    btn.style.cursor      = 'default';
    btn.style.opacity     = '0.85';
    btn.innerHTML = btn.dataset.month.slice(0,3) + '<br><span style="font-size:8px;font-weight:700">✓PAID</span>';
    btn.title = btn.dataset.month + ' — paid';
  }
  _fsDuesRowRecalc(rowId);
}

function _fsDuesRowRecalc(rowId) {
  const grid     = document.getElementById(`fs_drMonthGrid_${rowId}`);
  const amtEl    = document.getElementById(`fs_drAmt_${rowId}`);
  const countEl  = document.getElementById(`fs_drCount_${rowId}`);
  const rateEl   = document.getElementById(`fs_drRateLabel_${rowId}`);
  const prevCls  = document.getElementById(`fs_drCls_${rowId}`)?.value || '';
  if (!grid) return;

  const allBtns    = Array.from(grid.querySelectorAll('button[data-month]'));
  const unpaidMths = allBtns.filter(b => b.dataset.paid !== '1').map(b => b.dataset.month);
  const rate = prevCls ? _flRateForClass(prevCls, 0) : 0;   // L2/L8: one resolver
  const total = unpaidMths.length * rate;

  if (amtEl)   amtEl.value    = total > 0 ? total : '';
  if (countEl) countEl.textContent = unpaidMths.length > 0
    ? `${unpaidMths.length} unpaid month${unpaidMths.length > 1 ? 's' : ''}`
    : 'All paid — no dues';
  if (rateEl) {
    if (!prevCls)   rateEl.textContent = '← Select previous class first.';
    else if (!rate) rateEl.textContent = `No fee rate for ${prevCls}.`;
    else            rateEl.textContent = `₹${fmtNum(rate)}/mo (${prevCls}) × ${unpaidMths.length} unpaid =`;
  }
  _fsUpdateGrandTotal();
  _fsSerializeDues();
}

function _fsUpdateGrandTotal() {
  const container = document.getElementById('fs_prevDuesContainer');
  const gtWrap    = document.getElementById('fs_prevDuesGrandTotalWrap');
  const gtEl      = document.getElementById('fs_prevDuesGrandTotal');
  if (!container || !gtEl) return;

  const rows = container.querySelectorAll('[id^="fs_duesRow_"]');
  let grand = 0;
  rows.forEach(row => {
    const rid = row.id.replace('fs_duesRow_', '');
    const amt = parseFloat(document.getElementById(`fs_drAmt_${rid}`)?.value || 0);
    grand += amt;
  });

  if (gtEl) gtEl.textContent = '₹' + fmtNum(grand);
  if (gtWrap) gtWrap.style.display = grand > 0 || rows.length > 1 ? 'flex' : 'none';
}

// Serialize all dues rows into fs_prevDuesJson hidden field.
// Also back-fills legacy fields (fs_outstandingYearValue, fs_outstandingMonthsJson, fs_outstanding)
// from the FIRST row so saveStudent()'s existing read still works.
function _fsSerializeDues() {
  const container = document.getElementById('fs_prevDuesContainer');
  if (!container) return;

  const rows = container.querySelectorAll('[id^="fs_duesRow_"]');
  const _fullToShort = {June:'Jun',July:'Jul',August:'Aug',September:'Sep',October:'Oct',
    November:'Nov',December:'Dec',January:'Jan',February:'Feb',March:'Mar',April:'Apr',May:'May'};

  const allDues = [];
  rows.forEach((row, idx) => {
    const rid     = row.id.replace('fs_duesRow_', '');
    const cls     = document.getElementById(`fs_drCls_${rid}`)?.value || '';
    const yr      = document.getElementById(`fs_drYear_${rid}`)?.value || '';
    const amt     = parseFloat(document.getElementById(`fs_drAmt_${rid}`)?.value || 0);
    const grid    = document.getElementById(`fs_drMonthGrid_${rid}`);
    if (!yr) return; // skip incomplete rows

    const allBtns    = grid ? Array.from(grid.querySelectorAll('button[data-month]')) : [];
    const unpaidMths = allBtns.filter(b => b.dataset.paid !== '1').map(b => b.dataset.month);
    const monthStatus = {};
    allBtns.forEach(btn => {
      const sk = _fullToShort[btn.dataset.month] || btn.dataset.month;
      monthStatus[sk] = btn.dataset.paid === '1' ? 'N/A-PAID' : 'DUE';
    });

    allDues.push({ class: cls, year: yr, amount: amt, unpaidMonths: unpaidMths, monthStatus });

    // Back-fill legacy hidden fields from row 0 (first row)
    if (idx === 0) {
      const yvEl = document.getElementById('fs_outstandingYearValue');
      const mhEl = document.getElementById('fs_outstandingMonthsJson');
      const amEl = document.getElementById('fs_outstanding');
      if (yvEl) yvEl.value = yr;
      if (mhEl) mhEl.value = JSON.stringify(unpaidMths);
      if (amEl) amEl.value = amt || '';
    }
  });

  const jsonEl = document.getElementById('fs_prevDuesJson');
  if (jsonEl) jsonEl.value = JSON.stringify(allDues);
}

// Stub: old single-year helpers — kept so any residual calls don't throw
function _fsOutstandingYearChange() {}
function _fsOutstandingToggleMonth() {}
function _fsOutstandingRecalc() {}
// ── END MULTI-YEAR DUES SYSTEM ───────────────────────────────────────────────

// ── CURRENT YEAR DUES HELPERS ────────────────────────────────────────────────
// NEW LOGIC: ALL elapsed months start RED (unpaid/due) by default.
// Admin clicks months that ARE PAID → GREEN + locked.
// The unclicked RED months = dues stored in currentYearDueMonths.
function _fsCurYearRebuildGrid() {
  const grid      = document.getElementById('fs_curYearMonthGrid');
  const balEl     = document.getElementById('fs_curYearBalance');
  const countEl   = document.getElementById('fs_curYearMonthCount');
  const rateLabel = document.getElementById('fs_curYearRateLabel');
  const hidden    = document.getElementById('fs_curYearMonthsJson');
  if (!grid) return;

  // Reset hidden fields and totals
  if (hidden)  hidden.value  = '[]';
  if (balEl)   balEl.value   = '';
  if (countEl) countEl.textContent = '';

  const cls  = document.getElementById('fs_class')?.value || '';
  const rate = cls ? _flRateForClass(cls, 0) : 0;   // L2/L8: one resolver

  if (!cls || !rate) {
    grid.innerHTML = '<div style="font-size:12px;color:var(--muted);padding:6px 0">Select the student\'s class above to see month pills.</div>';
    if (rateLabel) rateLabel.textContent = '';
    return;
  }

  // Build month list Jun→May; only show months up to (and including) the current month
  const MONTHS = ['June','July','August','September','October','November','December',
                  'January','February','March','April','May'];
  const now        = nowIST(); /* ITEM 01 FIX: IST, not device timezone */
  const curMonth   = now.getMonth(); // 0=Jan … 11=Dec

  // Map calendar month index to academic sequence index (June=0 … May=11)
  function toAcadIdx(calIdx) {
    return calIdx >= 5 ? calIdx - 5 : calIdx + 7;
  }
  const currentAcadIdx = toAcadIdx(curMonth);

  // Only render months Jun→current month
  const available = MONTHS.slice(0, currentAcadIdx + 1);

  // ALL months start RED (unpaid/due) — admin clicks to mark GREEN (paid)
  grid.innerHTML = available.map(m => `
    <button type="button"
      data-month="${m}"
      data-paid="0"
      onclick="_fsCurYearToggleMonth(this)"
      style="padding:7px 4px;border-radius:8px;border:1px solid rgba(224,82,82,0.55);
             background:rgba(224,82,82,0.15);backdrop-filter:blur(4px);
             color:var(--danger);font-size:12px;font-weight:600;cursor:pointer;
             transition:all 0.15s ease;text-align:center;"
      title="${m} — unpaid (click to mark as paid)">
      ${m.slice(0,3)}
    </button>`).join('');

  if (rateLabel) rateLabel.textContent = cls ? `Rate: ₹${fmtNum(rate)}/month (${cls})` : '';
  _fsCurYearRecalc();
}

// REVERSED: clicking marks a month as PAID (green locked). Un-clicking → RED unpaid.
function _fsCurYearToggleMonth(btn) {
  const isPaid = btn.dataset.paid === '1';
  if (isPaid) {
    btn.dataset.paid  = '0';
    btn.style.background  = 'rgba(224,82,82,0.15)';
    btn.style.borderColor = 'rgba(224,82,82,0.55)';
    btn.style.color       = 'var(--danger)';
    btn.style.cursor      = 'pointer';
    btn.style.opacity     = '1';
    btn.innerHTML = btn.dataset.month.slice(0,3);
    btn.title = btn.dataset.month + ' — unpaid (click to mark as paid)';
  } else {
    btn.dataset.paid  = '1';
    btn.style.background  = 'rgba(82,200,122,0.18)';
    btn.style.borderColor = 'rgba(82,200,122,0.55)';
    btn.style.color       = 'var(--success)';
    btn.style.cursor      = 'default';
    btn.style.opacity     = '0.85';
    btn.innerHTML = btn.dataset.month.slice(0,3) + '<br><span style="font-size:8px;letter-spacing:0.5px;font-weight:700">✓ PAID</span>';
    btn.title = btn.dataset.month + ' — marked as paid';
  }
  _fsCurYearRecalc();
}

function _fsCurYearRecalc() {
  const grid      = document.getElementById('fs_curYearMonthGrid');
  const balEl     = document.getElementById('fs_curYearBalance');
  const countEl   = document.getElementById('fs_curYearMonthCount');
  const rateLabel = document.getElementById('fs_curYearRateLabel');
  const hidden    = document.getElementById('fs_curYearMonthsJson');
  if (!grid) return;

  // REVERSED: unpaid = months NOT marked paid (data-paid != '1')
  const allBtns      = Array.from(grid.querySelectorAll('button[data-month]'));
  const unpaidMonths = allBtns.filter(b => b.dataset.paid !== '1').map(b => b.dataset.month);
  if (hidden) hidden.value = JSON.stringify(unpaidMonths);

  const cls  = document.getElementById('fs_class')?.value || '';
  const rate = cls ? _flRateForClass(cls, 0) : 0;   // L2/L8: one resolver
  const total = unpaidMonths.length * rate;

  if (balEl)   balEl.value = total > 0 ? total : '';
  if (countEl) countEl.textContent = unpaidMonths.length > 0
    ? `${unpaidMonths.length} unpaid month${unpaidMonths.length !== 1 ? 's' : ''} × ₹${fmtNum(rate)} = ₹${fmtNum(total)} due`
    : 'All months paid — no current dues';
  if (rateLabel) rateLabel.textContent = cls && rate
    ? `Rate: ₹${fmtNum(rate)}/month (${cls})`
    : '';
}
// ── END CURRENT YEAR DUES HELPERS ────────────────────────────────────────────

async function saveStudent(isExisting) {
  // ITEM 11 FIX (Duplicate Student Records on Double-Click Import):
  // Guard against double/rapid-repeat clicks at the submission-handler level.
  // A module-level in-flight flag blocks re-entrant calls even if the click
  // handler somehow fires twice before the DOM update below takes effect,
  // and disabling the button removes the visual affordance to click again.
  if (saveStudent._inFlight) return;
  saveStudent._inFlight = true;
  const _saveBtn = document.getElementById('saveStudentBtn');
  const _saveBtnOrigHTML = _saveBtn ? _saveBtn.innerHTML : null;
  if (_saveBtn) {
    _saveBtn.disabled = true;
    _saveBtn.style.pointerEvents = 'none';
    _saveBtn.style.opacity = '0.6';
    _saveBtn.innerHTML = `${iconPlus} ${isExisting ? 'Importing…' : 'Saving…'}`;
  }
  try {
  // COLONEL'S CHANGE #2: feeSno removed per CHG-006. dob/pen/address/previousSchool/feeWaiver also removed previously.
  // CHG-014: admissionDate re-added as a required field for the stat card & audit purposes
  const admissionDateRaw = getVal('fs_admissionDate');
  const data = {
    name:           getVal('fs_name'),
    gender:         getVal('fs_gender'),
    block:          getVal('fs_block'),
    class:          getVal('fs_class'),
    section:        getVal('fs_section'),
    // [CHG-020] rollNumber removed
    admissionNumber:getVal('fs_admNo'),
    parentName:     getVal('fs_parent'),
    contact:        getVal('fs_contact'),
    status:         'active',
    createdAt:      firebase.firestore.FieldValue.serverTimestamp(),
    createdBy:      currentUser.uid,
    type:           isExisting ? 'existing' : 'new',
    // CHG-014: store admissionDate as Timestamp; default to today if blank
    admissionDate:  admissionDateRaw
      // ITEM: date-only fact — anchored at 12:00 IST via the shared converter, not
      // UTC midnight (which stores 05:30 IST and can tip onto the wrong day).
      ? istTimestampFromDateInput(admissionDateRaw, 'noon')
      : firebase.firestore.FieldValue.serverTimestamp()
  };
  if (isExisting) {
    // BUG-M07 FIX: monthlyFee is derived from the locked fee schedule, not from DOM input.
    // This prevents staff from manually entering a wrong monthly fee for existing students.
    // L2/L8: through the ONE resolver — a class name with stray whitespace would
    // otherwise store a monthlyFee of 0 on a brand-new student, and every screen
    // would then price them from that zero.
    data.monthlyFee         = (typeof _flRateForClass === 'function')
                                ? _flRateForClass(data.class, 0)
                                : _flRateForClass(data.class, 0);   // L2/L8: one resolver

    // ── MULTI-YEAR DUES: read fs_prevDuesJson (array of all previous-year rows) ──
    const allPrevDues = JSON.parse(document.getElementById('fs_prevDuesJson')?.value || '[]');
    let totalPrevBalance = 0;

    if (allPrevDues.length > 0) {
      // Store the full multi-year array for future reference
      data.openingOutstandingDues = allPrevDues;

      // For backward-compat: populate legacy single-year fields from the OLDEST year
      // (oldest = lowest year number) so _classifyDueYear & Past Due module still work.
      const sorted = [...allPrevDues].sort((a, b) => {
        const ya = parseInt((a.year||'').split('-')[0] || '0');
        const yb = parseInt((b.year||'').split('-')[0] || '0');
        return ya - yb; // ascending — oldest first
      });
      const oldest = sorted[0];
      data.openingOutstandingYear   = oldest.year;
      data.openingOutstandingClass  = oldest.class || data.class;
      data.openingOutstandingMonths = oldest.unpaidMonths || [];
      data.academicYear             = oldest.year;
      data.prevYearMonthStatus      = oldest.monthStatus || {};

      // outstandingBalance = sum of all previous-year dues
      totalPrevBalance = allPrevDues.reduce((s, r) => s + (r.amount || 0), 0);
      data.outstandingBalance = totalPrevBalance;
    } else {
      // Fallback: try legacy single-row fields (backward compat with old saves)
      const outstandingYear    = document.getElementById('fs_outstandingYearValue')?.value || '';
      const outstandingMonths  = JSON.parse(document.getElementById('fs_outstandingMonthsJson')?.value || '[]');
      const outstandingPrevCls = document.getElementById('fs_outstandingPrevClass')?.value || '';
      data.outstandingBalance  = parseFloat(document.getElementById('fs_outstanding')?.value || 0);
      if (outstandingYear && outstandingMonths.length > 0) {
        data.openingOutstandingYear   = outstandingYear;
        data.openingOutstandingMonths = outstandingMonths;
        data.openingOutstandingClass  = outstandingPrevCls || data.class;
        data.academicYear             = outstandingYear;
      }
    }

    // BUG-④ FIX: legacy prevYearMonthStatus build from first row's grid (kept for old path)
    const prevMonthGrid = document.getElementById('fs_outstandingMonthGrid');
    const outstandingYear = document.getElementById('fs_outstandingYearValue')?.value || '';
    if (prevMonthGrid && outstandingYear && allPrevDues.length === 0) {
      const _fullToShort = {
        June:'Jun', July:'Jul', August:'Aug', September:'Sep', October:'Oct',
        November:'Nov', December:'Dec', January:'Jan', February:'Feb',
        March:'Mar', April:'Apr', May:'May'
      };
      const monthStatus = {};
      prevMonthGrid.querySelectorAll('button[data-month]').forEach(btn => {
        const shortKey = _fullToShort[btn.dataset.month] || btn.dataset.month;
        monthStatus[shortKey] = btn.dataset.paid === '1' ? 'N/A-PAID' : 'DUE';
      });
      data.prevYearMonthStatus = monthStatus;
    }

    // ── Current-year dues ────────────────────────────────────────────────────
    // Read months selected in the Current Year Dues section.
    // These are stored separately from openingOutstanding (which is prior-year).
    // academicYear is always set to the current year so _classifyDueYear() returns
    // 'current' and the Accumulated Rolling Dues stat card picks this student up.
    const curYearMonths  = JSON.parse(document.getElementById('fs_curYearMonthsJson')?.value || '[]');
    const curYearBalance = parseFloat(document.getElementById('fs_curYearBalance')?.value || 0) || 0;
    const curAcadYear    = _getCurrentAcademicYearStr();

    // JSS-REF-VELTRIX-2026-003 ITEM 08.2 FIX: fs_curYearMonthsJson only ever stored
    // the UNPAID months (currentYearDueMonths below). Months the admin clicked green
    // (already paid before entry, e.g. June/July) were never written to Firestore at
    // all — so Record Payment's paid-months lookup (~line 5899 fetchPaidMonthsForCurrentYear)
    // had nothing to read them from, and those already-paid months re-appeared as
    // outstanding when the payment grid loaded. Read the grid directly and persist
    // the paid side too.
    const curYearGrid = document.getElementById('fs_curYearMonthGrid');
    const curYearPaidAtEntry = curYearGrid
      ? Array.from(curYearGrid.querySelectorAll('button[data-month]'))
          .filter(b => b.dataset.paid === '1')
          .map(b => b.dataset.month)
      : [];

    // JSS-REF-VELTRIX-2026-003 ITEM 08.2 FIX: store paid-at-entry months whenever the
    // grid was shown, independent of whether any months are still due, so a student
    // onboarded with ALL current-year months already paid also gets this recorded.
    if (curYearPaidAtEntry.length > 0) {
      data.currentYearPaidMonths = curYearPaidAtEntry;
      data.currentYearDueYear    = curAcadYear;
    }

    if (curYearMonths.length > 0) {
      data.currentYearDueMonths  = curYearMonths;
      data.currentYearDueBalance = curYearBalance;
      data.currentYearDueYear    = curAcadYear;  // ← store year label explicitly for future matching
      // If the student ALSO has previous-year debt, academicYear was already set above
      // to the previous year. Override it to current so _classifyDueYear() picks up
      // the current-year dues correctly. Previous-year dues are tracked separately via
      // openingOutstandingYear / openingOutstandingMonths fields.
      data.academicYear          = curAcadYear;
      // outstandingBalance = prev-year balance + current-year balance combined
      // so the Due Fee page shows the full picture in one number.
      data.outstandingBalance    = (data.outstandingBalance || 0) + curYearBalance;
    } else if (!data.academicYear) {
      // No dues entered at all — still tag with current year so this student is
      // visible in current-year views once payments start.
      data.academicYear = curAcadYear;
    }
  }

  // Validation — COLONEL'S CHANGE #2: removed dob, pen from required list
  // CHG-014: admissionDate re-added as required
  // [CHG-016]: admissionNumber removed from required — auto-generated by system
  const required = ['name','gender','block','class','section','parentName','contact'];
  for (const f of required) {
    if (!data[f]) {
      showFormAlert('addStudentAlert', `Please fill in all required fields (marked with *).`, 'danger');
      document.getElementById('addStudentAlert')?.scrollIntoView({ behavior:'smooth', block:'center' });
      return;
    }
  }
  if (!admissionDateRaw) {
    showFormAlert('addStudentAlert', 'Please select a Date of Admission.', 'danger');
    document.getElementById('addStudentAlert')?.scrollIntoView({ behavior:'smooth', block:'center' });
    return;
  }

  // BUG-M13 / DOUBLE-ENTRY FIX:
  // For isExisting=true (Onboard Existing Student): if the student already exists
  // in Firestore (matched by admission number), UPDATE their fee/dues data only —
  // never create a duplicate record. Identity fields (name, gender, class, etc.)
  // are NOT overwritten; only fee-related fields are merged in.
  // For isExisting=false (New Admission): block on duplicate admission number as before.
  try {
    if (data.admissionNumber) {
      const dupAdm = await schoolCol('students').where('admissionNumber','==',data.admissionNumber).get();
      if (!dupAdm.empty) {
        if (isExisting) {
          // ── EXISTING STUDENT PATH: update fee data only, no new record ──────
          const existingDoc  = dupAdm.docs[0];
          const existingId   = existingDoc.id;
          // Build a fee-only update payload — never clobber identity fields
          const feeUpdate = { updatedBy: currentUser.uid, updatedAt: firebase.firestore.FieldValue.serverTimestamp() };
          const feeFields = [
            'monthlyFee','outstandingBalance','openingOutstandingYear',
            'openingOutstandingMonths','openingOutstandingClass','academicYear',
            'currentYearDueMonths','currentYearDueBalance','currentYearDueYear','currentYearPaidMonths','remainingBalance',
            'monthStatus','totalDue','monthsDue','monthsCleared','fee_status',
            'openingOutstandingDues','prevYearMonthStatus'
          ];
          feeFields.forEach(f => { if (data[f] !== undefined) feeUpdate[f] = data[f]; });
          await schoolCol('students').doc(existingId).update(feeUpdate);

          // ══════════════════════════════════════════════════════════════════════
          // F6 — ONBOARD EXISTING STUDENT WROTE FEE DATA AND NEVER RECONCILED.
          //
          // This path writes SIXTEEN fee fields straight onto a live student:
          // outstandingBalance, monthStatus, openingOutstandingDues, totalDue,
          // monthsDue, fee_status and the rest. All of it from the admission form's
          // own arithmetic -- a separate computation of what a student owes -- and
          // then it invalidated the caches and returned.
          //
          // Invalidating a cache makes the next read re-fetch the STORED figure. It
          // does not recompute it. So every screen faithfully redisplayed whatever
          // the form had just guessed, and outstandingBalance stayed at the form's
          // number until some unrelated payment happened to trigger a real recompute.
          //
          // The NEW ADMISSION path a few lines below has always called _flReconcile.
          // This branch was written as its sibling and never got one. Item 17 admits
          // no exceptions, and this was one of them.
          //
          // Non-fatal by construction: the write has already succeeded, and
          // _flReconcile never throws. A failure here leaves exactly the state that
          // existed before this block, and says so.
          // ══════════════════════════════════════════════════════════════════════
          if (typeof _flReconcile === 'function') {
            await _flReconcile(existingId, 'onboard_existing_student');
          }
          schoolCol('academicStructure').doc(`${data.class}-${data.section}`).set({
            className: data.class, section: data.section,
            studentIds: firebase.firestore.FieldValue.arrayUnion(existingId)
          }, { merge:true }).catch(() => {});
          invalidateStudentCache();
          invalidateFinanceCache();
          window._cachedDynamicYears = null;
          showFormAlert('addStudentAlert', '✅ Fee/dues data updated for existing student.', 'success');
          document.getElementById('addStudentAlert')?.scrollIntoView({ behavior:'smooth', block:'center' });
          setTimeout(() => pushNav('studentProfile', { id: existingId }), 1200);
          return;
        } else {
          // ── NEW ADMISSION PATH: block duplicate as before ──────────────────
          showFormAlert('addStudentAlert', `⚠ Admission Number "${data.admissionNumber}" is already registered. Each student must have a unique Admission Number.`, 'danger');
          document.getElementById('addStudentAlert')?.scrollIntoView({ behavior:'smooth', block:'center' });
          return;
        }
      }
    }
    // ADM-FIX: If admissionNumber is blank at save time, generate the next sequential
    // number using the STUDENT'S OWN admission year — not the current calendar year.
    // Source of year (priority): admissionDate field → outstandingYear → current year.
    if (!data.admissionNumber) {
      let admYear = String(nowIST().getFullYear());
      if (admissionDateRaw) {
        admYear = String(new Date(admissionDateRaw).getFullYear());
      } else if (data.academicYear) {
        admYear = String(data.academicYear).split('-')[0];
      } else if (data.openingOutstandingYear) {
        admYear = String(data.openingOutstandingYear).split('-')[0];
      }
      data.admissionNumber = await generateNextAdmNoForYear(admYear);
    }

    const ref = await schoolCol('students').add(data);

    // BUG-08 FIX: academicStructure update is NON-BLOCKING — student save
    // succeeds even if this fails (permissions issue or network hiccup)
    schoolCol('academicStructure').doc(`${data.class}-${data.section}`).set({
      className: data.class, section: data.section,
      studentIds: firebase.firestore.FieldValue.arrayUnion(ref.id)
    }, { merge:true }).catch(() => { /* academicStructure update failed silently — student was saved */ });

    // ══════════════════════════════════════════════════════════════════════════
    // JSS-REF-VELTRIX-2026-005 ITEM 17 — "new admission" is named in the rule.
    //
    // Admission seeds outstandingBalance from the form's own arithmetic (opening
    // dues, current-year due months, months paid at enrolment). That is a THIRD
    // computation of what a student owes, written straight to the authoritative
    // field and never checked against the engine that every screen reads. Any
    // disagreement — a month grid and a scalar that do not add up, a rate the form
    // resolved differently — became the student's permanent opening position.
    //
    // Reconciling immediately after creation makes the engine the author of that
    // number, exactly as it is for every student thereafter. The form's arithmetic
    // becomes the INPUT (grids and paid months), not the answer.
    // ══════════════════════════════════════════════════════════════════════════
    if (typeof _flReconcile === 'function') await _flReconcile(ref.id, 'new_admission');

    showFormAlert('addStudentAlert', '✅ Student saved successfully!', 'success');
    document.getElementById('addStudentAlert')?.scrollIntoView({ behavior:'smooth', block:'center' });
    invalidateStudentCache();  // clear student cache so new student appears in search immediately
    invalidateFinanceCache();  // BUG-H04 FIX: dashboard + academic stats stale after new student added
    window._cachedDynamicYears = null; // ✦ POINT 2: refresh dynamic year list after new student
    setTimeout(() => pushNav('studentProfile', { id:ref.id }), 1200);
  } catch(e) {
    showFormAlert('addStudentAlert', 'Error saving student: ' + e.message, 'danger');
    document.getElementById('addStudentAlert')?.scrollIntoView({ behavior:'smooth', block:'center' });
  }
  } finally {
    // ITEM 11 FIX: always release the in-flight guard and restore the button,
    // regardless of which return/throw path was taken above, so a genuine
    // retry after a validation error or network failure is still possible —
    // only true concurrent double-clicks are blocked.
    saveStudent._inFlight = false;
    if (_saveBtn) {
      _saveBtn.disabled = false;
      _saveBtn.style.pointerEvents = '';
      _saveBtn.style.opacity = '';
      if (_saveBtnOrigHTML !== null) _saveBtn.innerHTML = _saveBtnOrigHTML;
    }
  }
}

